### ISSUE TITLE
User can break joining process by swiping back from username screen

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1757]

**Comment by adrastaea** [comment]
This is fixed

**Comment by kingalg** [comment]
It seems that it's partially fixed. Now, when you follow the steps listed by @holmesworcester, this happens: **the user can go back but is not stuck. Joining or creating an account can be repeated without the need to restart the app.** 

It's no longer causing the app to break, so I would consider it fixed; however, it doesn't meet all requirements (the user can still go back).

Is this solution fine with you, @holmesworcester, or do you want to keep it open and disable the "back" function?

**Comment by holmesworcester** [comment]
This is still annoying and worth fixing.
