### ISSUE TITLE
Javascript Injection / Code Execution in the Input Box

### ISSUE THREAD

**Issue by s-rah** [TryQuiet/quiet#744]
Copy and pasting `<img src=x onerror=alert(2) />` into the message box results in an Alert Window `2` popping up

Copy and pasting `<img src=x onerror=window.open("https://www.example.com/") />` results in the complete webpage being loaded.

Tested on quiet@0.8.6

**Comment by holmesworcester** [comment]
Note: we should fix these on master and release an update before 2.0

**Comment by EmiM** [comment]
I confirm that it still exists in quiet@1.9.4

https://github.com/TryQuiet/quiet/pull/1943

**Comment by kingalg** [comment]
Version: 1.9.5

I've checked it on fixed production Version: 1.9.5 on MacOs, Windows and Linux and I couldn't inject the code anymore. Fixed.

**Comment by s-rah** [comment]
While the trivial cases no longer work, the underlying issue has not been fixed - there are numerous ways of getting html into the clipboard which when pasted will result in code injection (among other things):

![Screenshot_2023-10-13_15-03-53](https://github.com/TryQuiet/quiet/assets/106626/ec98388f-2549-4efd-8e31-2bf8172fecee)

**Comment by holmesworcester** [comment]
Thanks @s-rah. @EmiM let's reopen this issue rather than creating a new one so that s-rah will continue to get updates.

**Comment by EmiM** [comment]
@s-rah thank you! Could you provide some examples? They would be helpful for creating tests after sanitizing html.

**Comment by EmiM** [comment]
Ok, I managed to create one example that executes js inside our input so we can check it after releasing the fix

![Screenshot from 2023-10-17 12-36-03](https://github.com/TryQuiet/quiet/assets/6099829/1ee5db66-3e70-4576-82a2-23c0ef4ff573)

**Comment by kingalg** [comment]
quiet@2.0.3-alpha.0

I've checked new solution from @EmiM and it does solve problem that we see on production in version: 1.9.5. We are aware that tracking this is ongoing challange but for now I'm closing this issue as methods pointed in it are no longer working after fixes. In case of discovering any new ways of making Javascript Injection / Code Execution in the Input Box possible we will be either re-opening this issue or creating new one.
